import { Inter } from 'next/font/google';
import Providers from '../components/Providers';
import NavBar from '../components/Navbar';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <div className='container h-full'>
            <h1 className='text-6xl font-semibold my-5 text-center'>Pokedex</h1>
            {children}
          </div>

        </Providers>
      </body>
    </html>
  )
}
